### TEST GET / WEBSITE
GET http://localhost:5003

### TEST GET / ARTICLES
GET http://localhost:5003/articles

### TEST POST / ARTICLES
POST http://localhost:5003/articles
Content-Type: application/json

{
  "title": "LFG",
  "tags": "beam,light,bright",
  "content": "I Love JS"
}

### TEST UPDATE / ARTICLES/1
PUT http://localhost:5003/articles/1
Content-Type: application/json

{
  "title": "Cam",
  "content": "I FW "
}

### TEST DELETE / ARTICLES/1
DELETE http://localhost:5003/articles/1



